### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by janxious**
Speed! Takes noticeable time to compute the list somewhere between 10000 and 100000.

### CODE REVIEW

**Comment by stevegrossi** [comment]
Thanks for this, @janxious! It's interesting walking through your commits to see how your thoughts evolved on this. I ran some benchmarks (with [alco/benchfella](https://github.com/alco/benchfella)) on my initial solution, your polished solution with the private `compute` method, and your final solution using `Stream.unfold/2`:

```
benchmark name                iterations   average time

## My initial solution
Fibonacci.series(10)              500000   4.37 µs/op
Fibonacci.series(25)                 500   5090.30 µs/op

## Your solution with `compute`
Fibonacci.compute_series(10)    10000000   0.21 µs/op
Fibonacci.compute_series(25)    10000000   0.57 µs/op

## Your solution with `Stream.unfold/2`
Fibonacci.unfold_series(10)      1000000   1.20 µs/op
Fibonacci.unfold_series(25)      1000000   2.26 µs/op
```

Interestingly, `Stream.unfold/2` ended up being about 5x slower. What are your thoughts on rolling back that last commit which switched to `Stream`?

Alternatively, I think `Fibonacci.stream` would be useful as a separate public function in this library for when laziness is called for.

**Comment by stevegrossi** [comment]
Benchmarking further, I'm seeing the performance of your custom `compute` approach and `Stream.unfold/2` converge at much higher values of `length` (at which my initial approach melts down):

```
# 50k

Fibonacci.compute_series(50000)          10   103448.60 µs/op
Fibonacci.unfold_series(50000)           10   108037.20 µs/op

# 65k

Fibonacci.compute_series(65000)           5   280019.00 µs/op
Fibonacci.unfold_series(65000)            5   281063.80 µs/op

# 75k

Fibonacci.unfold_series(75000)            2   512527.00 µs/op
Fibonacci.compute_series(75000)           2   615537.00 µs/op
```

On my machine at least, the inflection point is around 65k, after which `Stream.unfold/2` is faster.

**Comment by stevegrossi** [comment]
I feel like the performance difference is more important at higher values of `length` (who cares about a difference of `1µs`? Even if that's half an order of magnitude when length is `10`—you can always cache the value), which tips be back in favor of this PR's current incarnation with `Stream.unfold`. So I'll plan on merging that unless you feel differently.

**Comment by stevegrossi** [comment]
Oh wait, they appear to inflect again around `85k`, after which point your custom `compute` function becomes faster once again!

``` elixir
# 85k

Fibonacci.unfold_series(85000)            1   1024793.00 µs/op
Fibonacci.compute_series(85000)           1   1027772.00 µs/op

# 100k

Fibonacci.compute_series(100000)           1   1183933.00 µs/op
Fibonacci.unfold_series(100000)            1   1562331.00 µs/op

# 125k
Fibonacci.compute_series(125000)           1   1863827.00 µs/op
Fibonacci.unfold_series(125000)            1   2266858.00 µs/op

# 150k - unfold is faster again!
Fibonacci.unfold_series(150000)            1   3164412.00 µs/op
Fibonacci.compute_series(150000)           1   3304900.00 µs/op
```

Very curious performance characteristics... I'm not doing anything else on my computer which would add noise to these results. And while these later benchmarks only perform one iteration, I'm re-running them a few times and getting nearly the same results.

**Comment by janxious** [comment]
> Alternatively, I think Fibonacci.stream would be useful as a separate public function in this library for when laziness is called for.

Funny you should mention that. I actually wanted the implementation to be based on infinite streams so it would be easier to write some other functions dealing with fib numbers, and I felt like my first cut – whilst much faster than the initial implementation – lacked all finesse.

---

My benchmarking was of the sort: "Can I compute the first 500K fib numbers before the heat death of the universe?". The solutions presented in the commits for this PR all meet that standard, so 😸 and your choice which one you like.

---

You can see perhaps why I ended up where I did when you look at #5, and the trivial nature of implementation.

**Comment by stevegrossi** [comment]
https://github.com/stevegrossi/fibonacci/pull/5 was where I imagined this ending up, so I'll merge this and move on to that. Thanks!

**Pull request merged**
